### ISSUE TITLE
content?

### ISSUE THREAD

**Issue by dcsan** [stephenmccready/chinese#1]
seems to be missing!

i'm just starting to work on a similar thing, actually for wechat browser...
https://github.com/dcsan/chinese-study

**Comment by dcsan** [comment]
do you know any other good open source resources for this type of content?

**Comment by stephenmccready** [comment]
Just a placeholder at the moment - it's a work in progress.
I use [http://www.zein.se/patrick/3000char.html](http://www.zein.se/patrick/3000char.html) and [http://www.chineasy.com/](http://www.chineasy.com/). There are lots of places on-line to download the mandarin sound files.

**Comment by dcsan** [comment]
thanks. what about sources for wordlists or sentence examples, esp organized around grammar?
eg I built this thing a long time back:   www.jgram.org
and wanted to do similar for chinese. but apart from pulling apart anki decks I havent found a good simple source for material.

**Comment by stephenmccready** [comment]
I found good resources in about.com - especially [http://mandarin.about.com/bio/Qiu-Gui-Su-27591.htm](http://mandarin.about.com/bio/Qiu-Gui-Su-27591.htm)
